name: build-and-release
on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install

      # Новый шаг: очистка файла от невидимых символов
      - name: Sanitize source
        run: |
          echo "Cleaning src/Verter.user.js..."
          F=src/Verter.user.js
          perl -CSD -pe 's/\x{FEFF}|\x{200B}//g' -i "$F"
          perl -CSD -pe "s/\x{2026}/.../g" -i "$F"
          perl -CSD -pe "tr/\x{2013}\x{2014}/--/" -i "$F"
          perl -CSD -pe "tr/\x{2018}\x{2019}\x{201C}\x{201D}/''\"\"/" -i "$F"

      - name: PCS (syntax + lint + build)
        run: npm run pcs

      - name: Pack
        run: bash pack.sh

      - name: Upload artifact (named)
        uses: actions/upload-artifact@v4
        with:
          name: verter-named
          path: |
            build/*.zip
            build/ARTIFACT_NAME.txt
            build/RELEASE_TAG.txt
            build/RELEASE_TITLE.txt
          if-no-files-found: error

      - name: Upload artifact (compat)
        uses: actions/upload-artifact@v4
        with:
          name: verter-safe
          path: build/Verter_SAFE.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          name: Verter ver. 2.2 — OrderGate+VirtFix
          files: build/*.zip
